common:
  batch_size: 256
  image_size: [96, 96]
  is_restore: False
  restore_ind: ""
  restore_ckpt: ""
  preview_batch: 1000

global_settings:
  image_size: [96, 96]

trainer:
  max_epochs: 20
  precision: 32
  val_check_interval: 1.0
  gradient_clip_val: 5
  accumulate_grad_batches: 1
  accelerator: gpu
  devices: [0]

model:
  name: ClassifierModel
  backbone:
    name: Backbone
    options:
      name: lcnet_050
      pretrained: True
      features_only: True
      replace_components: True
  head:
    name: FeatureLearningHead
    options:
      in_dim: 256
  loss:
    name: ArcFace
    options:
      s: 64
      m: 0.4
    num_classes: -1
    embed_dim: 128

onnx:
  name: WarpFeatureLearning
  input_shape:
    img:
      shape: [1, 3, 96, 96]
      dtype: float32
  input_names: ['img']
  output_names:
    - feats
  # dynamic_axes:
  #   img:
  #     '0': batch_size
  #   output:
  #     '0': batch_size
  options:
    opset_version: 16
    verbose: False
    do_constant_folding: True

quantize:
  do_quant: False

dataset:
  train_options:
    name: SyncDataset
    options:
      aug_ratio: 1
      length_of_dataset: 256000
  valid_options:
    name: RealDataset
    options:
      return_tensor: True

dataloader:
  train_options:
    batch_size: -1
    num_workers: 16
    shuffle: False
    drop_last: False
  valid_options:
    batch_size: -1
    num_workers: 16
    shuffle: False
    drop_last: False

optimizer:
  name: AdamW
  options:
    lr: 1.0e-3
    betas: [0.9, 0.999]
    weight_decay: 0.1
    amsgrad: False

lr_scheduler:
  name: PolynomialLRWarmup
  options:
    warmup_iters: -1
    total_iters: -1
  pl_options:
    monitor: loss
    interval: step

callbacks:
  - name: ModelCheckpoint
    options:
      monitor: valid_auc
      mode: max
      verbose: True
      save_last: True
      save_top_k: 5
  - name: LearningRateMonitor
    options:
      logging_interval: step
  - name: RichModelSummary
    options:
      max_depth: 3
  - name: CustomTQDMProgressBar
    options:
      unit_scale: -1

logger:
  name: TensorBoardLogger
  options:
    save_dir: logger
